name: Send morning email

on:
  schedule:
    - cron: '15 8 * * *'  # rulează zilnic la 08:15 UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run morning email script
        run: node morning_email.js

      - name: Upload email log
        uses: actions/upload-artifact@v3
        with:
          name: email-log
          path: email_log.txt
